name: Build and Push Docker Images on Release

on:
  release:
    types: [published]

env:
  REGISTRY: docker.io

jobs:
  build-and-push:
    environment: docker-publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [relay-server, reverse-proxy, entry-point]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          build-args: |
            BUILD_APP=${{ matrix.app }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.app }}:${{ github.ref_name }}
